oc:
    resource: "../../src/Oc/"
    type:     annotation

oc_dev:
    resource: "../../src/OcDev/"
    type:     annotation

best_it_kitchensink:
    resource: "@BestItKitchensinkBundle/resources/config/routing.yml"
